<?php
declare(strict_types=1);

return [
    'groups' => [
        'inpost' => [
            'label' => 'InPost',
            'sort' => 10,
        ],
        'dpd' => [
            'label' => 'DPD',
            'sort' => 20,
        ],
        'gls' => [
            'label' => 'GLS',
            'sort' => 30,
        ],
        'orlen' => [
            'label' => 'ORLEN',
            'sort' => 40,
        ],
        'allegro_one' => [
            'label' => 'Allegro One',
            'sort' => 50,
        ],
        'dhl' => [
            'label' => 'DHL',
            'sort' => 60,
        ],
        'erli' => [
            'label' => 'ERLI',
            'sort' => 70,
        ],
        'odbior_osobisty' => [
            'label' => 'Odbiór osobisty',
            'sort' => 80,
        ],
        'inne' => [
            'label' => 'Inne',
            'sort' => 999,
        ],
    ],

    'rules' => [

        // ODBIÓR OSOBISTY
        [
            'rule_code' => 'odbior_osobisty',
            'match_type' => 'regex',
            'match_value' => '/odbiór osobisty|odbior osobisty|odbiór w sklepie|odbior w sklepie|odbiór osobisty w punkcie sprzedawcy|odbior osobisty w punkcie sprzedawcy|odbiór w sklepie po otrzymaniu sms|odbior w sklepie po otrzymaniu sms/iu',
            'menu_group' => 'odbior_osobisty',
            'shipment_type' => 'odbior_osobisty',
            'label_provider' => 'none',
            'label_endpoint' => 'shipping.none',
            'requires_size' => false,
            'priority' => 2000,
            'active' => true,
        ],

        // ERLI - zawsze przez BaseLinker
        [
            'rule_code' => 'erli_inpost_paczkomat',
            'match_type' => 'contains',
            'match_value' => 'ERLI InPost Paczkomaty',
            'menu_group' => 'inpost',
            'shipment_type' => 'erli_inpost_paczkomat',
            'label_provider' => 'baselinker_api',
            'label_endpoint' => 'shipping.baselinker.createPackage',
            'requires_size' => true,
            'priority' => 1000,
            'active' => true,
        ],
        [
            'rule_code' => 'erli_inpost_kurier',
            'match_type' => 'contains',
            'match_value' => 'ERLI InPost Kurier',
            'menu_group' => 'inpost',
            'shipment_type' => 'erli_inpost_kurier',
            'label_provider' => 'baselinker_api',
            'label_endpoint' => 'shipping.baselinker.createPackage',
            'requires_size' => false,
            'priority' => 1000,
            'active' => true,
        ],
        [
            'rule_code' => 'erli_dhl',
            'match_type' => 'contains',
            'match_value' => 'ERLI DHL',
            'menu_group' => 'dhl',
            'shipment_type' => 'erli_dhl',
            'label_provider' => 'baselinker_api',
            'label_endpoint' => 'shipping.baselinker.createPackage',
            'requires_size' => false,
            'priority' => 1000,
            'active' => true,
        ],
        [
            'rule_code' => 'erli_dpd',
            'match_type' => 'contains',
            'match_value' => 'ERLI DPD',
            'menu_group' => 'dpd',
            'shipment_type' => 'erli_dpd',
            'label_provider' => 'baselinker_api',
            'label_endpoint' => 'shipping.baselinker.createPackage',
            'requires_size' => false,
            'priority' => 1000,
            'active' => true,
        ],

        // ALLEGRO ONE
        [
            'rule_code' => 'allegro_one_dpd',
            'match_type' => 'contains',
            'match_value' => 'One Box, DPD',
            'menu_group' => 'allegro_one',
            'shipment_type' => 'allegro_one_box_dpd',
            'label_provider' => 'allegro_api',
            'label_endpoint' => 'shipping.allegro.createShipment',
            'requires_size' => false,
            'priority' => 950,
            'active' => true,
        ],
        [
            'rule_code' => 'allegro_one_punkt_dpd',
            'match_type' => 'contains',
            'match_value' => 'One Punkt, DPD',
            'menu_group' => 'allegro_one',
            'shipment_type' => 'allegro_one_punkt_dpd',
            'label_provider' => 'allegro_api',
            'label_endpoint' => 'shipping.allegro.createShipment',
            'requires_size' => false,
            'priority' => 950,
            'active' => true,
        ],
        [
            'rule_code' => 'allegro_one_default',
            'match_type' => 'contains',
            'match_value' => 'One ',
            'menu_group' => 'allegro_one',
            'shipment_type' => 'allegro_one',
            'label_provider' => 'allegro_api',
            'label_endpoint' => 'shipping.allegro.createShipment',
            'requires_size' => false,
            'priority' => 900,
            'active' => true,
        ],



        // ALLEGRO INTERNATIONAL ONE (Czechy/Słowacja/Węgry przez kuriera ONE)
        [
            'rule_code' => 'allegro_international_one',
            'match_type' => 'contains',
            'match_value' => 'Allegro International',
            'menu_group' => 'allegro_one',
            'menu_label' => 'Allegro ONE',
            'shipment_type' => 'allegro_international_one',
            'label_provider' => 'allegro_api',
            'label_endpoint' => 'shipping.allegro.createShipment',
            'requires_size' => false,
            'priority' => 950,
            'active' => true,
            'must_also_match_any' => ['One'],
        ],


        // ALLEGRO ONE BOX DPD - przycisk dpd, etykieta przez allegro
        [
            'rule_code' => 'allegro_one_box_dpd',
            'match_type' => 'contains',
            'match_value' => 'Allegro One Box, DPD',
            'menu_group' => 'dpd',
            'menu_label' => 'DPD',
            'shipment_type' => 'allegro_one_box_dpd',
            'label_provider' => 'allegro_api',
            'label_endpoint' => 'shipping.allegro.createShipment',
            'requires_size' => false,
            'priority' => 960,
            'active' => true,
        ],

        // ALLEGRO ONE PUNKT DPD - przycisk dpd, etykieta przez allegro
        [
            'rule_code' => 'allegro_one_punkt_dpd',
            'match_type' => 'contains',
            'match_value' => 'Allegro One Punkt, DPD',
            'menu_group' => 'dpd',
            'menu_label' => 'DPD',
            'shipment_type' => 'allegro_one_punkt_dpd',
            'label_provider' => 'allegro_api',
            'label_endpoint' => 'shipping.allegro.createShipment',
            'requires_size' => false,
            'priority' => 960,
            'active' => true,
        ],

        // ALLEGRO DHL - zawsze przez allegro_api
        [
            'rule_code' => 'allegro_dhl',
            'match_type' => 'contains',
            'match_value' => 'Allegro',
            'menu_group' => 'dhl',
            'shipment_type' => 'allegro_dhl',
            'label_provider' => 'allegro_api',
            'label_endpoint' => 'shipping.allegro.createShipment',
            'requires_size' => false,
            'priority' => 870,
            'active' => true,
            'must_also_match_any' => ['DHL'],
        ],

        // ALLEGRO ORLEN / PACKETA / WYSYLKA ZAGRANICZNA - zawsze przez allegro_api
        [
            'rule_code' => 'allegro_orlen',
            'match_type' => 'contains',
            'match_value' => 'Allegro',
            'menu_group' => 'orlen',
            'shipment_type' => 'allegro_orlen',
            'label_provider' => 'allegro_api',
            'label_endpoint' => 'shipping.allegro.createShipment',
            'requires_size' => false,
            'priority' => 870,
            'active' => true,
            'must_also_match_any' => ['ORLEN', 'Packeta', 'Wysyłka z Polski'],
        ],

        // ALLEGRO DPD
        [
            'rule_code' => 'allegro_dpd_pickup',
            'match_type' => 'contains',
            'match_value' => 'DPD Pickup',
            'menu_group' => 'dpd',
            'shipment_type' => 'allegro_dpd_pickup',
            'label_provider' => 'allegro_api',
            'label_endpoint' => 'shipping.allegro.createShipment',
            'requires_size' => false,
            'priority' => 880,
            'must_also_match_any' => ['Allegro'],
            'active' => true,
        ],
        [
            'rule_code' => 'allegro_dpd',
            'match_type' => 'contains',
            'match_value' => 'Allegro',
            'menu_group' => 'dpd',
            'shipment_type' => 'allegro_dpd',
            'label_provider' => 'allegro_api',
            'label_endpoint' => 'shipping.allegro.createShipment',
            'requires_size' => false,
            'priority' => 870,
            'active' => true,
            'must_also_match_any' => ['DPD'],
        ],

        // ALLEGRO INPOST
        [
            'rule_code' => 'allegro_inpost_paczkomat',
            'match_type' => 'contains',
            'match_value' => 'Allegro Paczkomaty InPost',
            'menu_group' => 'inpost',
            'shipment_type' => 'allegro_inpost_paczkomat',
            'label_provider' => 'inpost_shipx',
            'label_endpoint' => 'shipping.inpost.createShipment',
            'requires_size' => true,
            'priority' => 920,
            'active' => true,
        ],
        [
            'rule_code' => 'allegro_inpost_kurier',
            'match_type' => 'contains',
            'match_value' => 'InPost',
            'menu_group' => 'inpost',
            'shipment_type' => 'allegro_inpost',
            'label_provider' => 'allegro_api',
            'label_endpoint' => 'shipping.allegro.createShipment',
            'requires_size' => false,
            'priority' => 860,
            'active' => true,
            'must_also_match_any' => ['Allegro'],
        ],

        // ZWYKŁY INPOST
        [
            'rule_code' => 'inpost_paczkomat',
            'match_type' => 'regex',
            'match_value' => '/paczkomat|paczkomaty inpost|paczkomaty|automat(?:y)? paczkowe.*inpost/iu',
            'menu_group' => 'inpost',
            'shipment_type' => 'inpost_paczkomat',
            'label_provider' => 'inpost_shipx',
            'label_endpoint' => 'shipping.inpost.createShipment',
            'requires_size' => true,
            'priority' => 850,
            'active' => true,
        ],
        [
            'rule_code' => 'inpost_kurier',
            'match_type' => 'regex',
            'match_value' => '/inpostkurier|kurier inpost|minikurier24 inpost|kurier24 inpost/iu',
            'menu_group' => 'inpost',
            'shipment_type' => 'inpost_kurier',
            'label_provider' => 'inpost_shipx',
            'label_endpoint' => 'shipping.inpost.createShipment',
            'requires_size' => false,
            'priority' => 840,
            'active' => true,
        ],

        // ZWYKŁY DPD
        [
            'rule_code' => 'dpd_pickup',
            'match_type' => 'regex',
            'match_value' => '/dpd pickup|dpd pickup pobranie|dpd automat|automat.*dpd|dpd pickup słowacja|dpd pickup slowacja/iu',
            'menu_group' => 'dpd',
            'shipment_type' => 'dpd_pickup',
            'label_provider' => 'dpd_api',
            'label_endpoint' => 'shipping.dpd.createPackage',
            'requires_size' => false,
            'priority' => 830,
            'active' => true,
        ],
        [
            'rule_code' => 'dpd_seller_agreed',
            'match_type' => 'contains',
            'match_value' => 'Dostawa i jej koszt ustalane ze sprzedającym',
            'menu_group' => 'dpd',
            'shipment_type' => 'dpd_manual_agreed',
            'label_provider' => 'dpd_api',
            'label_endpoint' => 'shipping.dpd.createPackage',
            'requires_size' => false,
            'priority' => 821,
            'active' => true,
        ],
        [
            'rule_code' => 'dpd_kurier',
            'match_type' => 'regex',
            'match_value' => '/\bdpd\b|kurier dpd|dpd pobranie|kurier dpd pobranie|dpd dłużyca|dpd dluzyca/iu',
            'menu_group' => 'dpd',
            'shipment_type' => 'dpd_kurier',
            'label_provider' => 'dpd_api',
            'label_endpoint' => 'shipping.dpd.createPackage',
            'requires_size' => false,
            'priority' => 820,
            'active' => true,
        ],

        // GLS + ogólna kurierska + same kraje
        [
            'rule_code' => 'gls_generic_courier',
            'match_type' => 'regex',
            'match_value' => '/przesyłka kurierska|przesylka kurierska|przesyłka kurierska pobranie|przesylka kurierska pobranie|^kurier$|kurier pobranie|^czechy$|^słowacja$|^slowacja$|^węgry$|^wegry$/iu',
            'menu_group' => 'gls',
            'shipment_type' => 'gls_generic',
            'label_provider' => 'gls_api',
            'label_endpoint' => 'shipping.gls.createShipment',
            'requires_size' => false,
            'priority' => 815,
            'active' => true,
        ],
        [
            'rule_code' => 'gls',
            'match_type' => 'regex',
            'match_value' => '/\bgls\b|kurier gls|gls parcel shop/iu',
            'menu_group' => 'gls',
            'shipment_type' => 'gls',
            'label_provider' => 'gls_api',
            'label_endpoint' => 'shipping.gls.createShipment',
            'requires_size' => false,
            'priority' => 810,
            'active' => true,
        ],

        // DHL
        [
            'rule_code' => 'dhl',
            'match_type' => 'regex',
            'match_value' => '/\bdhl\b|dhl box|punkt.*dhl|odbiór w punkcie dhl|odbior w punkcie dhl/iu',
            'menu_group' => 'dhl',
            'shipment_type' => 'dhl',
            'label_provider' => 'dhl_api',
            'label_endpoint' => 'shipping.dhl.createShipment',
            'requires_size' => false,
            'priority' => 800,
            'active' => true,
        ],

        // ORLEN / PACKETA
        [
            'rule_code' => 'orlen_packeta',
            'match_type' => 'regex',
            'match_value' => '/orlen|packeta/iu',
            'menu_group' => 'orlen',
            'shipment_type' => 'orlen_packeta',
            'label_provider' => 'orlen_api',
            'label_endpoint' => 'shipping.orlen.createShipment',
            'requires_size' => false,
            'priority' => 790,
            'active' => true,
        ],
    ],
];
